name: Build APK MADFAZ Music

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-android:
    runs-on: ubuntu-22.04 

    steps:
      - name: Tarik kode aplikasi (Checkout)
        uses: actions/checkout@v4

      - name: Setup Python (Siapin Mesin)
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies (Siapin Alat Masak)
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev

      - name: Install Buildozer (Panggil Koki)
        run: |
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Masak APK (Mulai Kompilasi Auto-Yes)
        # Tambahin "yes |" biar robotnya otomatis setuju lisensi Android
        run: yes | buildozer android debug

      - name: Simpan Hasil APK (Panen)
        uses: actions/upload-artifact@v4
        with:
          name: MADFAZ-Music-APK
          path: bin/*.apk
          
